### ISSUE TITLE
Orientation part 2

### ISSUE THREAD

**Issue by DaveCamp96** [hackforla/.github#1]
Hi Bonnie, I had something come up last night and unfortunately had to miss the second part of orientation. Will there be another session coming up that I could join?
Apologies if this is the wrong method of reaching you. Just hoping to get back in motion and involved as soon as I can!

Thanks,
David Campanella

**Comment by kcoronel** [comment]
Hi @DaveCamp96 please join the next onboarding on August 15, feel free to come 45mins into the meeting (so 6:45pm) 

Here is the link to [RSVP](https://www.meetup.com/hackforla/events/vfknzsyfcjbjc/)
